### ISSUE TITLE
How can I find the zro module needed for VisualStim.py?

### ISSUE THREAD

**Issue by hillierdani** [zhuangjun1981/coricalmapping#1]
I ran setup.py, then I try to run VisualStim.py but after many attempts I still do not have a clue which python package would satisfy this dependency:
from zro import RemoteObject, Proxy

**Comment by zhuangjun1981** [comment]
This repo is just my personal backup of my local code base. We are currently working on adding VisualStim to a more formal github repo "https://github.com/zhuangjun1981/retinotopic_mapping". It will not depend on zro. I believe it will be out in a few month.

**Comment by hillierdani** [comment]
Great, thanks a lot for your efforts!

**Comment by zhuangjun1981** [comment]
the retinotopic_mapping package now can display mapping and other visual stimuli. Check it out if you are interested. 

https://github.com/zhuangjun1981/retinotopic_mapping

**Comment by hillierdani** [comment]
Thank you, I appreciate your care! ---------------------------------------------------- Hillier Dániel 

    Le Samedi 15 juillet 2017 2h00, zhuangjun1981 <notifications@github.com> a écrit :
 

 the retinotopic_mapping package now can display mapping and other visual stimuli. Check it out if you are interested.https://github.com/zhuangjun1981/retinotopic_mapping—
